version: 0.2

phases:
    build: 
      commands:
      - echo "this is build phase..."

    post_build:
       commands:
      - echo "deployed to s3"
artifacts:
    files:
      - '**/*'
